### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xwvu** [kieronia/Fortnite-Username-Checker#1]
im kinda new to python and Im not sure what im doing wrong
here is whats happening:

"

== RESTART: C:\Users\admin\Desktop\Fortnite-Username-Checker-master\Checker.py =
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\Fortnite-Username-Checker-master\Checker.py", line 1, in <module>
    from colorama import Fore, init, Style
ModuleNotFoundError: No module named 'colorama'
>>> 

"

**Comment by kieronia** [comment]
Open cmd and type 
pip install colorama 
If it works, for everyone word after import, just try pip install it until you've attempted all, then re run it. If problems still occur 
Try uninstalling python and reinstalling, ticking any boxes about path and pip and then try the project again. Hope this helps and please consider starring and following

**Comment by x0v** [comment]
please contact discord colin💍#0666
very new to python and have no clue how to get this working.
